title: "Zeta IT Tools"
subtitle: "Internal Access Panel"
logo: "logo.png"
header: true
footer: false
theme: default
columns: true  # ✅ ENABLE MULTI-COLUMN DISPLAY

# ...

services:
  - name: "Zeta IT Tools"
    icon: "fas fa-network-wired"
    layout: columns  # ✅ USE COLUMN LAYOUT
    items:
      - name: "Email Portal"
        url: "http://corpitmail.internal.directi.com/edp2user"
        icon: "fas fa-envelope"
      - name: "Gsuite Portal"
        url: "http://172.16.140.222/zeta/modify/#"
        icon: "fas fa-user-cog"
      - name: "Zeta OCS"
        url: "https://bcon.supporthub.tech/"
        icon: "fas fa-cloud"
      - name: "VMOBI OCS"
        url: "https://fcon.supporthub.tech/"
        icon: "fas fa-cloud"
      - name: "Directi OCS"
        url: "https://dcon.supporthub.tech/"
        icon: "fas fa-cloud"
      - name: "Redmine Ticket"
        url: "https://ithelpdesk.directi.com/my/page"
        icon: "fas fa-ticket-alt"
      - name: "Zeta Snipe IT"
        url: "https://h-zeta.internal.directi.com/"
        icon: "fas fa-desktop"
      - name: "Directi Snipe IT"
        url: "https://h-directi.internal.directi.com/login"
        icon: "fas fa-desktop"
      - name: "VMOBI Snipe IT"
        url: "https://h-vmobi.internal.directi.com/"
        icon: "fas fa-desktop"
      - name: "EPP Download"
        url: "http://172.16.64.63/client.php/software"
        icon: "fas fa-download"
      - name: "Zeta SSP Portal"
        url: "https://ssp.corp.zeta.tech/"
        icon: "fas fa-user-shield"
      - name: "Flock SSP Portal"
        url: "https://fpassword.corp.flock.com/"
        icon: "fas fa-key"
      - name: "Jira Portal"
        url: "https://zeta-tm.atlassian.net"
        icon: "fab fa-jira"
      - name: "External VPN"
        url: "https://blr-vpn.ext.zeta.tech/"
        icon: "fas fa-shield-alt"
      - name: "IT Share Drive"
        url: "http://172.16.64.81"
        icon: "fas fa-folder"
      - name: "Udemy Learning"
        url: "https://corpteams.udemy.com"
        icon: "fas fa-graduation-cap"
      - name: "SSL VPN"
        url: "https://sslvpn.zeta.in"
        icon: "fas fa-lock"
      - name: "SSL VPN 2"
        url: "https://sslvpn2.zeta.in"
        icon: "fas fa-lock"
      - name: "Directi SSL VPN"
        url: "https://ssl.vpn.directi.com"
        icon: "fas fa-lock"
      - name: "Ops SSL VPN"
        url: "https://sslvpn.ops.directi.com"
        icon: "fas fa-lock"
      - name: "Zeta Reset Portal"
        url: "https://172.16.65.149/"
        icon: "fas fa-sync"
      - name: "McAfee Portal"
        url: "https://mcafee.com"
        icon: "fas fa-virus"
      - name: "Microsoft Login"
        url: "https://login.microsoftonline.com/"
        icon: "fab fa-microsoft"
      - name: "Jetbrains Login"
        url: "https://account.jetbrains.com/login"
        icon: "fas fa-code"
      - name: "EPP Admin"
        url: "https://epp-blr.internal.zeta.in/"
        icon: "fas fa-tools"
      - name: "Directi SSP"
        url: "https://password.internal.directi.com/"
        icon: "fas fa-user-lock"
      - name: "Kaspersky Directi"
        url: "https://cloud.kaspersky.com/#/companies/all"
        icon: "fas fa-shield-virus"
      - name: "ManageEngine"
        url: "https://endpointcentral.manageengine.in/webclient"
        icon: "fas fa-cogs"
      - name: "New EPP Portal"
        url: "https://i6lob4q.hosted.endpointprotector.com"
        icon: "fas fa-broadcast-tower"
      - name: "Zeta KAV Portal"
        url: "https://ksc.kaspersky.com/"
        icon: "fas fa-shield-alt"
