services:

  - name: "Portals"
    icon: "fas fa-network-wired"
    layout: columns
    items:
      - name: "Email Portal"
        url: "http://corpitmail.internal.directi.com/edp2user"
        icon: "fas fa-envelope"
      - name: "Corp IT Portal"
        url: "https://zetaworld.sharepoint.com/sites/CorporateIT-ITHelpdesk/SitePages/CorpIT-Email.aspx"
        icon: "fas fa-paper-plane"  # Quick email-like icon

  - name: "License Management"
    icon: "fas fa-id-badge"
    layout: columns
    items:
      - name: "Adobe Login"
        url: "https://directi.com/adobe-login"
        icon: "fas fa-paint-brush"
      - name: "JetBrains"
        url: "https://account.jetbrains.com/login"
        icon: "fas fa-code"
      - name: "EPP Admin"
        url: "https://epp-blr.internal.zeta.in/"
        icon: "fas fa-user-shield"
      - name: "Directi SSP"
        url: "https://password.internal.directi.com/"
        icon: "fas fa-key"
      - name: "KAV Portal"
        url: "https://cloud.kaspersky.com/#/companies/all"
        icon: "fas fa-shield-alt"
      - name: "ManageEngine"
        url: "https://endpointcentral.manageengine.in/webclient"
        icon: "fas fa-cogs"
      - name: "Zeta KAV Portal"
        url: "https://ksc.kaspersky.com/"
        icon: "fas fa-virus-slash"

  - name: "System Administration"
    icon: "fas fa-server"
    layout: columns
    items:
      - name: "New EPP Portal (DLP)"
        url: "https://i6lob4q.hosted.endpointprotector.com"
        icon: "fas fa-exclamation-triangle"
      - name: "Azure Admin Portal"
        url: "https://portal.azure.com/"
        icon: "fab fa-microsoft"
      - name: "Gsuite Postal"
        url: "http://172.16.140.222/zeta/modify/#"
        icon: "fab fa-google"
      - name: "Google Admin"
        url: "https://admin.google.com"
        icon: "fab fa-google"

  - name: "Asset Inventory"
    icon: "fas fa-boxes"
    layout: columns
    items:
      - name: "Zeta Snipe IT"
        url: "https://h-zeta.internal.directi.com/"
        icon: "fas fa-desktop"
      - name: "Directi Snipe IT"
        url: "https://h-directi.internal.directi.com/login"
        icon: "fas fa-desktop"
      - name: "VMOBI Snipe IT"
        url: "https://h-vmobi.internal.directi.com/"
        icon: "fas fa-desktop"
      - name: "Radix Snipe IT"
        url: "https://h-radix.internal.directi.com/"
        icon: "fas fa-desktop"
      - name: "BWDSPL Snipe IT"
        url: "https://h-bwdspl.internal.directi.com/"
        icon: "fas fa-desktop"
      - name: "Zeta OCS"
        url: "https://bcon.supporthub.tech/"
        icon: "fas fa-network-wired"
      - name: "VMOBI OCS"
        url: "https://fcon.supporthub.tech/"
        icon: "fas fa-network-wired"
      - name: "Directi OCS"
        url: "https://dcon.supporthub.tech/"
        icon: "fas fa-network-wired"
